version: '2.0'
services:
  docker-demo-web:
    ports: ["8080:8080"]
    image: "docker-demo:1.0"
    container_name: docker-demo

  docker-demo-redis:
    image: "redis"
    volumes: ["/docker/host/dir:/data"]
    command: redis-server
    container_name: redis
